### ISSUE TITLE
Get Maven to compile tests separately from the package

### ISSUE THREAD

**Issue by skeet70** [Duelers/Duelers#202]
Currently, the tests are bundled with the software we release because the only way I could get maven to work is by adding the tests with the <compile> configuration.  Tests should be built independently of the actual project.

**Comment by QLaille** [comment]
We can either add `-Dmaven.test.skip=true` to the command when packaging with maven or add a line to the properties of the pom for maven to skip all tests.

**Comment by QLaille** [comment]
A PR is ready just in case.

**Comment by skeet70** [comment]
@fluffy-hamster could you clarify what this story is for? I think we should run tests whenever we package, so not #270. I was under the impression you were concerned that files we're getting added to the release that shouldn't be? I can't tell where though. The `src/test/java` pattern is pretty normal if that was your concern, normally all the code in in `src/main/java/*` and tests are in `src/test/java/*`.

**Comment by QLaille** [comment]
Closing this issue as after letting it simmer a bit I find it irrelevant, if you want to package without the test just add the appropriate option to the command.
