### ISSUE TITLE
revamp deck requirements

### ISSUE THREAD

**Issue by skeet70** [Duelers/Duelers#206]
Currently, in order for a deck to be considered valid it must need 1 hero (aka general) , 20 minions and one item. I want these requirements changed so that a valid deck must have a combination of minions, artifacts and spells totaling up to 39 and one general, for a total of 40 cards in the deck.

Notes:
-Artifacts do not exist in the current project and are instead replaced by items, which can be described as spells that are activated at the start of a match. Part of this card/ticket includes removing this feature from matches and from being required in a deck

**Comment by skeet70** [comment]
```
Chris Feb 23 at 2:27 AM
We may also want to support smaller/larger decks for debugging purposes.

e.g much easier to test fatigue when decks only have 3 cards.

Reply
Chris Feb 12 at 7:28 PM
I've removed the item requirement from deckbuilding in release preAlpha0.1

I'm planning on leaving the size at 20 for a while, given how small our current roster of cards is.
```

**Comment by Ridleh** [comment]
requirements have been revamped to allow decks of sizes 5-40
