### ISSUE TITLE
Add Default decks to account creation

### ISSUE THREAD

**Issue by skeet70** [Duelers/Duelers#213]
Adding decks to account creation allows us devs to work faster since we won't have to commit (and manage conflicts) on the duelyst account.

- [x] Add default decks to account creation. (Requirements: load decks from folder, decks are json files)
- [x] ensure any changes work with the import card python script.
- [x] Retire duelyst account
- [x] Ensure that at least one 'starter deck' works will with the AI (eg. no spells, no complex targeted effects etc)

**Comment by skeet70** [comment]
```
Chris yesterday at 11:45 AM
listed as high priority because I think solving this issue will make development faster. (fewer merge conflicts)
```

**Comment by QLaille** [comment]
By "Retire duelyst account", do you mean "Replace this class with something local" ?

**Comment by fluffy-hamster** [comment]
> By "Retire duelyst account", do you mean "Replace this class with something local" ?

What I mean if, once this change "goes live" there is almost no reason to care about the duelyst.json account.  So by retire I basically just mean delete.
