### ISSUE TITLE
Create docs site and port old documentation

### ISSUE THREAD

**Issue by skeet70** [Duelers/Duelers#218]
We need to pull all our documentation that is spread out over discord and google docs into github somehow. Maybe the wiki for user level docs and a doc site for developer docs?

ToDo:

- [ ] Subdirectories / pages
- [ ] Find easy solution to storing images.

**Comment by skeet70** [comment]
Copied from discord:

Does anyone have preferences between where on github we put dev/design/usage documentation? I think the good options are:

* wiki https://github.com/duelers/duelers/wiki, example https://github.com/magefree/mage/wiki
* github pages https://duelers.github.io/Duelers/, example http://owner.aeonbits.org/docs/welcome/ or something like https://thomasreinecke.github.io/git-playbook/#/playbook/process
* gitbook (should be free since we're OSS) https://www.gitbook.com/?t=2#ProductsDocs, example https://www.chartjs.org/docs/latest/

I did the little bit of work to get a basic github pages up, but I'd like input before working on porting the content anywhere. I think important things to consider are:

* how easy is it for people (users, developers, designers) to find the docs once they've found/been linked to the project
* how easy is it for non-developers to contribute documentation
* how nice is it to navigate and use (can I search for what I want easily? Is it pleasant to look at? etc)

@Anteron I agree gitbook has a lot of upsides, and we can publish it to our github pages thing so it'd be at duelers.github.io/Duelers too. I think you can also set it up with a WYSIWYG so non-developers could easily contribute docs.
It may just be that gitbook is the easy answer best of all worlds. I wasn't sure if people had a strong preference for a wiki or something though.

**Comment by skeet70** [comment]
Created https://github.com/Duelers/Duelers/wiki and started porting existing documentation to it. Remaining files are:

[drive-download-20200302T114658Z-001.zip](https://github.com/Duelers/Duelers/files/4316010/drive-download-20200302T114658Z-001.zip)
[drive-download-20200302T114717Z-001.zip](https://github.com/Duelers/Duelers/files/4316011/drive-download-20200302T114717Z-001.zip)

**Comment by skeet70** [comment]
WRT adding images, it looks like you clone the automatically created wiki repo and add the resources to it, or you link directly to them if they're in the main repo https://gist.github.com/subfuzion/0d3f19c4f780a7d75ba2

**Comment by skeet70** [comment]
https://github.community/t5/How-to-use-Git-and-GitHub/Folders-or-grouping-pages-in-GitHub-Wikis/td-p/7633 talks about creating a sidebar with a hierarchy.

**Comment by fluffy-hamster** [comment]
Marking this as closed.  

Only two outstanding issues

1) Because gitwiki doesn't seem to have copy & paste support for images, I'll continue to use google drive for some docs.

2) Wiki could do with some sub directories.
