### ISSUE TITLE
The client can set current mp. That sounds wrong.

### ISSUE THREAD

**Issue by Qazzquimby** [Duelers/Duelers#391]
Nearly all object manipulation is done in the server to keep things synchronized and prevent tampering. Client has access to setting current mp in the Player class.
This may be acceptable to reduce the number of server pings, but I think it could be avoided.

**Comment by Qazzquimby** [comment]
Client can also add cards to graveyard (something server apparently can't do?), has a setTroops method that should be part of construction, and presumably other violations of its responsibilities.

**Comment by Ridleh** [comment]
We have server validations checking if the player has enough mana for a card, and i believe the setMana method is only used to update the UI
I do not know much about adding cards to the graveyard and setTroops method. will need to look into that

**Comment by fluffy-hamster** [comment]
if all setMana does it update the UI,  then it probably needs to be renamed as such.

or better yet, should probably be a property.

**Comment by fluffy-hamster** [comment]
@Qazzquimby  if this is no longer an issue, close the ticket.

**Comment by Qazzquimby** [comment]
Possibly reopening later. Not sure if its solved.
