### ISSUE TITLE
Add number of players online in client.

### ISSUE THREAD

**Issue by fluffy-hamster** [Duelers/Duelers#413]
Add info in client about number of players online, number in queue etc.

**Comment by fluffy-hamster** [comment]
@MaSer713   I presume there is an easy way to do this?

**Comment by MaSer713** [comment]
Not if you want to do it properly. You can always show the number of "online" people but some of they may not actually be online (timeout/quit without proper logout)

**Comment by fluffy-hamster** [comment]
@MaSer713  
I doesn't need to update in realtime (updating every 10 min would probably be fine). That said, the number would need to be somewhat accurate given the size of our playerbase.
  
Basically, I just thought this would help a bit with matchmaking and debugging.

But okay, if this is something that cannot be done with an hour of effort I'm willing to abandon the idea.

**Comment by fluffy-hamster** [comment]
Closing because it seems difficult todo
