### ISSUE TITLE
Read new cards from AppData

### ISSUE THREAD

**Issue by fluffy-hamster** [Duelers/Duelers#496]
Userstory:  As a user I want to be able to add my own cards to the game without the help of developers.

Solution:  Have the game load in cards/artwork from AppData

Requirements:
- [x] AppData can correctly import plist files, png files and json files. 
- [x] AppData can also import spell fx (see branch #488)
- [x] AppData cards can only be used when running in "local host mode"  
- [x] User Guide (written and/or video) explaining how to add art/cards

**Comment by Ridleh** [comment]
see #497

**Comment by Ridleh** [comment]
completed
